### ISSUE TITLE
src/arg_parse.d(330): Error: file "commit" cannot be found or not in a path specified with -J

### ISSUE THREAD

**Issue by pazthy** [funpopgen/CaVEMaN#1]
First my apologies if this is not the correct way to do it.
I am trying to compile Caveman ( dmd-2.075.0 ) and when I do:

 make dmd_test && make dmd

I get the following error:

~/dlang/dmd-2.075.0/linux/bin64/dmd -debug -g -unittest -w -Jviews src/main.d src/arg_parse.d src/read_data.d src/calculation.d src/run_analysis.d src/correct.d src/best.d src/weights.d src/interpolate.o -ofunittest
src/arg_parse.d(330): Error: file "commit" cannot be found or not in a path specified with -J
make: *** [dmd_test] Error 1

I am not sure what is this file commit.
Please advice.

**Comment by funpopgen** [comment]
Is git installed on your system? I think the command that is failing is this one:

git rev-parse --short HEAD > views/commit

If that command fails though, you can just run "touch views/commit" instead. Then make as usual and everything should work fine.

**Comment by pazthy** [comment]
Thank you so much!! Yes, this was the problem. I had though to use git to clone it and then:

mkdir views ; git rev-parse --short HEAD > views/commit

I could not make it work, from the zip file.
